# Global options
#debug: true
#env: 
#  HTTP_PROXY: http://myproxy
#  NO_PROXY: github.com

options:
  # print stats every 60 seconds 
  printStats: 60
  # don't write parsed logs to stdout
  suppress: false
  # Enable/disable GeoIP lookups
  # Startup of logagent might be slower, when downloading the GeoIP database
  geoipEnabled: false
  # Directory to store Logagent status and temporary files
  diskBufferDir: ./tmp

input:
  # a list of glob patterns to watch files to tail
  #files:
  #    - '/var/log/**/*.log'
  # listen to udp syslog protocol  
  syslog: 
    module: input-syslog
    port: 1514
    address: 127.0.0.0
  # Receive data from Heroku log drains via http
  #heroku: 
  #  port: 9999
  # Receive data from Cloud Foundry log drains via http  
  #cloudFoundry:
  #  port: 8888


# optional, if not specified default patterns are used
parser:
  #patternFiles:
    # load a list of pattern files to parse logs
    # later files overwrite settings from previous files
    #- patterns1.yml
    #- patterns2.yml
  # Inline pattern definitions are merged with default pattern list and can overwrite existing definitions
  patterns:
    - # timestamped messages from /var/log/*.log on Mac OS X
      sourceName: !!js/regexp /\system\.log/ # catch all system.log files  
      match:
        -
          type: system_log
          regex: !!js/regexp /([\w|\s]+\s+\d{2}\s[\d|\:]+)\s(.+?)\s(.+?)\s<(.+)>(.*)/
          fields: [ts,host,service,severity,message]
          dateFormat: MMM DD HH:mm:ss

output:
  # index logs in Elasticsearch or Logsene
  elasticsearch: 
    module: elasticsearch
    url: https://localhost:9200
    # default index to use, for all logs that don't match later in indices section
    index: 0a835c75-9847-4f74-xxxx
    # specific index to use per logSource field of parsed logs
    # logSource is by default the basename of the log file
    # but it can be modified by JS transforms functions in the patterns.yml file
    indices: 
      4f70a0c7-9458-43e2-bbc5-xxxx: 
      # list of RegEx matching logSource (e.g. file name, container image, container name, ...)  
      # all logs from this source will be indexed to above index
        - .*wifi.*
        - .*bluetooth.*
      999532c9-18f1-4c4b-8753-xxxx: 
        - system\.log
        - access\.log
        - auth\.log
  # print parsed logs in YAML format to stdout    
  stdout: yaml # use 'pretty' for pretty json and 'ldjson' for line delimited json (default)
  