# Kubernetes < v1.9
# apiVersion: extensions/v1beta1
# Kubernetes >= v1.9
# apiVersion: extensions/v1beta2
# Kubernetes v1.10
# apiVersion: apps/v1beta2
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sematext-logagent
spec:
  template:
    metadata:
      labels:
        app: sematext-logagent
    spec:
      nodeSelector: {}
      hostNetwork: true
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      containers:
      - name: sematext-logagent
        image: sematext/logagent:latest
        imagePullPolicy: "Always"
        env:
          - name: LOGS_TOKEN
            value: "YOUR_LOGS_TOKEN"
          - name: LOGS_RECEIVER_URL
            value: "https://logsene-receiver.sematext.com"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
          - mountPath: /etc/localtime
            name: localtime
#          - mountPath: /etc/logagent
#            name: patterns
        securityContext:
          privileged: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: localtime
          hostPath:
            path: /etc/localtime
#        - name: patterns
#          configMap:
#            name: sematext-agent-patterns
#            items:
#            - key: patterns.yml
#              path: patterns.yml
